### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by JosKrause** [tauhidm01/ToDoList-Application#1]
Here are my observations to your project, please note that the icons and meaning used are taken from: https://gitmoji.carloscuesta.me/.

Feel free to ignore and/or disagree!

### Remarks:

|Type|Comment|
|:-:|---|
|:art:| Consider using default folder structure for code repositories<br>- build, docs, sample, **src**, tests|
|:building_construction:|Any particular reason you choose **4.7.2** and not just .NET Core?|
|:lipstick:|Consider using **rem** units for CSS files for better scaling on devices|
|:lipstick:|Defining the [width of form controls](https://github.com/tauhidm01/ToDoList-Application/blob/master/ToDoList/Content/Site.css#L23) should be done using bootstrap grid|
|:pencil2:|Consider naming the Controller **TodoController** as there is no suitable plural to use here|
|:art:|Consider marking non-action methods with the `[NonAction]` attribute|
|:art:|Consider using `var` type declarations when the implicit type is obvious|
|:art:|Consider using `x.User.Id == currentUserId` to save an extra DB round-trip by not having to [retrieve `currentUser`](https://github.com/tauhidm01/ToDoList-Application/blob/master/ToDoList/Controllers/ToDoesController.cs#L31)|
|:art:|Consider using the `Enumerable.Count()` Func to [get the `completeCount` value](https://github.com/tauhidm01/ToDoList-Application/blob/master/ToDoList/Controllers/ToDoesController.cs#L33)|
|:art:|Consider adding `ToList()` to prevent the `myToDoes` from being enumerated multiple times (allocates enumerator)|
|:art:|Consider adding models classes for **Todo**|
|:art:|Consider adding data annotation attributes to model classes to trigger unobtrusive validation|

**Comment by tauhidm01** [comment]
No reason for using 4.7.2.
